import type { Block } from "./blocks";

export type ArticleCategory =
  | "levee-de-fonds"
  | "pacte-dactionnaires"
  | "fintech"
  | "donnees-personnelles"
  | "propriete-intellectuelle";

export type Article = {
  slug: string;
  title: string;
  date: string;
  author: string;
  categories: ArticleCategory[];
  excerpt: string;
  blocks: Block[];
};

export const CATEGORY_LABELS: Record<ArticleCategory, string> = {
  "levee-de-fonds": "Levée de fonds",
  "pacte-dactionnaires": "Pacte d'actionnaires",
  "fintech": "Fintech",
  "donnees-personnelles": "Données personnelles",
  "propriete-intellectuelle": "Propriété intellectuelle",
};

export const articles: Article[] = [
  {
    slug: "term-sheet-processus-levee-de-fonds",
    title: "La term sheet dans le processus de levée de fonds",
    date: "2021-01-29",
    author: "Sonia Mavouna",
    categories: ["levee-de-fonds"],
    excerpt: "Votre rendez-vous investisseur s'est bien passé, et vous allez recevoir prochainement une term sheet ?",
    blocks: [
      { t: "p", c: "Le pitch deck et le business plan de votre start-up sont prêts, et à jour ? Votre rendez-vous investisseur s'est bien passé, et vous allez recevoir prochainement une term sheet ? Appelée aussi lettre d'intention, c'est l'un des premiers documents signés dans le cadre d'une levée de fonds. Elle contient un récapitulatif des principales modalités juridiques et financières de l'investissement." },
      { t: "h2", c: "Clauses essentielles" },
      { t: "h3", c: "Convention d'investissement & pacte d'actionnaires" },
      { t: "ul", c: [
        "Identité des parties",
        "Montant d'investissement et valorisation avant opération",
        "Modalités de prise de participation (numéraire, nature, BSA, BSPCE)",
        "Décisions importantes soumises à accord investisseur",
        "Encadrement des cessions (préemption, lock-up, agrément)",
        "Dispositions financières (partage des profits, liquidation préférentielle)",
        "Clauses de sortie anticipée",
        "Gouvernance (conseil, président, DG)",
      ]},
      { t: "h3", c: "Obligations des parties" },
      { t: "ul", c: [
        "Confidentialité — interdiction de divulgation",
        "Information — transmission des données utiles",
        "Conditions de réalisation — audits, accords réglementaires",
        "Exclusivité — pas de négociation parallèle",
      ]},
      { t: "h2", c: "Enjeux juridiques" },
      { t: "p", c: "La rédaction est relativement libre. En pratique, c'est l'investisseur qui adresse le document ; faire appel à des avocats permet d'évaluer son caractère contraignant. En principe, la lettre d'intention est non-binding — elle exprime l'intention mutuelle sans engager contractuellement, à condition que ce caractère non-engageant apparaisse clairement." },
      { t: "p", c: "Réussir la négociation de sa term sheet est essentiel. Ce document fait partie intégrante de la documentation d'investissement." },
    ],
  },
  {
    slug: "typologies-levees-de-fonds-afrique-francophone",
    title: "Levée de fonds en Afrique francophone : comprendre les typologies",
    date: "2022-08-01",
    author: "ALF",
    categories: ["levee-de-fonds"],
    excerpt: "Seed, série A, série C — comprendre les différentes étapes d'une levée.",
    blocks: [
      { t: "h2", c: "Pre-seed" },
      { t: "p", c: "Le pre-seed ou amorçage précède le seed. C'est le premier financement destiné à lancer un projet de start-up." },
      { t: "ul", c: [
        "Réalisation du MVP (minimum viable product)",
        "Lancement produit/service pour collecter les premiers feedbacks",
        "Test du modèle économique",
      ]},
      { t: "h2", c: "Seed" },
      { t: "p", c: "Premier tour officiel, au moment où les premiers revenus apparaissent et qu'il faut continuer à développer pour tenir." },
      { t: "ul", c: [
        "Premières embauches",
        "Marketing et communication",
        "Renforcement commercial",
      ]},
      { t: "h2", c: "Série A" },
      { t: "p", c: "Après product-market fit, pour accélérer." },
      { t: "ul", c: [
        "Accélération de la croissance",
        "Conquête du marché national",
        "Recrutement accéléré",
        "Protection des innovations",
      ]},
      { t: "h2", c: "Série B" },
      { t: "ul", c: [
        "Tenir la croissance",
        "S'étendre à l'international",
        "Développer de nouvelles branches",
        "Acquérir des concurrents",
      ]},
      { t: "h2", c: "Série C" },
      { t: "p", c: "Pré-IPO : diversification et conquête du leadership international." },
      { t: "ul", c: ["Acquisitions", "Recrutements", "Internationalisation", "Diversification"]},
    ],
  },
  {
    slug: "negocier-term-sheet-droit-francais",
    title: "Comment négocier sa term sheet en droit français ?",
    date: "2022-02-03",
    author: "Sonia Mavouna",
    categories: ["levee-de-fonds"],
    excerpt: "Votre rendez-vous investisseur s'est bien passé — voici les clauses à négocier.",
    blocks: [
      { t: "h2", c: "Clauses essentielles de la term sheet" },
      { t: "h3", c: "Convention d'investissement & pacte d'actionnaires" },
      { t: "ul", c: [
        "Identité des parties et informations sociétaires",
        "Montant et valorisation pre/post-opération",
        "Modalités de participation (numéraire, nature, BSA Ratchet, BSPCE)",
        "Durée de négociation minimale/maximale",
        "Caractère engageant ou non du document",
        "Confidentialité",
        "Droit applicable et tribunal compétent",
        "Cap table avant/après investissement",
      ]},
      { t: "p", c: "Le pacte d'actionnaires doit spécifier : décisions importantes, encadrement des cessions (préemption, agrément, lock-up), partage des profits et liquidation préférentielle, clauses de sortie anticipée, gouvernance, droits préférentiels, engagements fondateurs (good/bad leaver), PI et non-concurrence." },
      { t: "h3", c: "Obligations des parties" },
      { t: "ul", c: [
        "Confidentialité vis-à-vis des tiers",
        "Information — transmission des données utiles",
        "Conditions de réalisation (audits, accords réglementaires)",
        "Exclusivité — pas de négociations parallèles",
      ]},
      { t: "h2", c: "Impact sur le personnel" },
      { t: "p", c: "Les investisseurs peuvent négocier le maintien, le départ ou la modification des conditions du personnel clé. Les mécanismes d'intéressement (management package) sont courants pour les cadres dirigeants." },
      { t: "h2", c: "Signature" },
      { t: "p", c: "La term sheet doit être signée par la société, ses principaux actionnaires, les fondateurs participants et les investisseurs existants." },
      { t: "h2", c: "Enjeux juridiques" },
      { t: "p", c: "En principe non-binding : elle manifeste la volonté mutuelle de réaliser la levée sans engagement contractuel formel." },
      { t: "h2", c: "Rupture de négociations" },
      { t: "p", c: "Les parties peuvent librement rompre selon l'article 1112 du Code civil, mais doivent respecter la bonne foi. Responsabilité engagée en cas d'intention de nuire (Civ. 1re, 12 avril 1976), de légèreté blâmable (Civ. 3e, 15 juin 2017), ou de pourparlers suffisamment avancés créant une attente raisonnable. À l'état d'ébauche : rupture libre (Civ. 1re, 20 décembre 2012)." },
      { t: "h2", c: "Sanctions" },
      { t: "p", c: "Dommages-intérêts. Article 1112 al. 2 du Code civil : « la réparation du préjudice ne peut avoir pour objet de compenser la perte des avantages attendus du contrat non conclu ». Sont éligibles à compensation les frais engagés (conseils, études, expertises, avocats, audits). Non éligibles : gain manqué, perte de chance de conclure." },
    ],
  },
  {
    slug: "6-conseils-preparer-levee-de-fonds",
    title: "6 conseils pour préparer votre levée de fonds en Afrique francophone",
    date: "2021-01-29",
    author: "Sonia Mavouna",
    categories: ["levee-de-fonds"],
    excerpt: "La majorité des entrepreneurs se mettent à la recherche de fonds au mauvais moment. Voici comment anticiper.",
    blocks: [
      { t: "h2", c: "1. Lever pour une bonne raison" },
      { t: "p", c: "Lever n'est pas une fin en soi. C'est un moyen pour l'entreprise de continuer à prendre des risques et à grandir. Gardez en tête la direction de votre société et le paysage concurrentiel." },
      { t: "h2", c: "2. Anticiper la recherche" },
      { t: "p", c: "Commencez au moins 6 à 9 mois avant que la trésorerie devienne critique. Calculez vos besoins réels sur les 12-18 prochains mois (recrutement, expansion, R&D)." },
      { t: "h2", c: "3. Désigner une personne dédiée" },
      { t: "p", c: "En général le CEO. Le reste de l'équipe reste concentré sur le revenu pendant la négociation." },
      { t: "h2", c: "4. Développer un réseau d'investisseurs" },
      { t: "p", c: "Cartographiez : secteur, stade de développement, tickets, géographie, portefeuille. Bâtissez des relations simples, intelligentes, basées sur la confiance." },
      { t: "h2", c: "5. Présenter avec clarté" },
      { t: "p", c: "Plan financier clair (dépenses, revenus, besoins, déploiement du capital). Storytelling et matériel de communication professionnels." },
      { t: "h2", c: "6. Détermination et bon entourage" },
      { t: "p", c: "Résilience, mentors expérimentés, maîtrise de la documentation d'investissement (term sheet, pacte)." },
    ],
  },
  {
    slug: "pacte-associes-fondateurs",
    title: "Le pacte d'associés fondateurs",
    date: "2021-01-29",
    author: "Sonia Mavouna",
    categories: ["pacte-dactionnaires"],
    excerpt: "Une image claire de l'équipe pour les investisseurs, un règlement intérieur pour les entrepreneurs.",
    blocks: [
      { t: "p", c: "Le pacte d'associés fondateurs est un contrat confidentiel signé entre les actionnaires cofondateurs de la société. Il diffère des statuts (publics, axés sur la vie sociale) et du pacte d'actionnaires signé avec les investisseurs lors d'une levée de fonds." },
      { t: "h2", c: "Objectifs" },
      { t: "h3", c: "Modalités de direction et de gestion" },
      { t: "ul", c: [
        "Comment les décisions sont-elles prises ?",
        "Qui représente la société vis-à-vis des tiers ?",
        "Les fondateurs peuvent-ils travailler ailleurs ?",
      ]},
      { t: "h3", c: "Conditions d'entrée et de sortie du capital" },
      { t: "ul", c: [
        "À qui et à partir de quand revendre ses actions ?",
        "Dans quels cas un fondateur doit-il restituer ses actions ?",
      ]},
      { t: "h3", c: "Image de l'équipe aux investisseurs" },
      { t: "p", c: "Avant une levée, le pacte donne aux investisseurs une vision du fonctionnement. Veillez à un pacte clair et équilibré." },
      { t: "h3", c: "Sanctions en cas de non-respect" },
      { t: "p", c: "Versement de dommages-intérêts aux actionnaires victimes ; la jurisprudence a pu accorder l'exécution forcée." },
      { t: "h2", c: "Clauses principales" },
      { t: "h3", c: "Préemption" },
      { t: "p", c: "Un actionnaire qui cède ses actions doit les proposer en priorité aux autres associés au même prix." },
      { t: "h3", c: "Agrément" },
      { t: "p", c: "Soumet une cession à l'agrément préalable des autres actionnaires ou d'un organe social." },
      { t: "h3", c: "Propriété intellectuelle" },
      { t: "p", c: "Cession à la société des droits patrimoniaux d'auteur réalisés dans le cadre des activités." },
      { t: "h3", c: "Non-concurrence" },
      { t: "p", c: "Interdiction d'activité concurrente pendant une certaine durée ; engagement à consacrer l'essentiel de son temps à la start-up." },
      { t: "h3", c: "Exclusion" },
      { t: "p", c: "Permet d'exclure un actionnaire dirigeant en cas de comportement non conforme (violation de confidentialité, non-concurrence...)." },
      { t: "h3", c: "Good leaver / bad leaver" },
      { t: "p", c: "Durée minimale d'engagement. Celui qui part avant est sanctionné (cession à prix défavorable) ; celui qui respecte est récompensé." },
      { t: "p", c: "Autres clauses possibles : liquidité, drag along, gouvernance, information/contrôle." },
    ],
  },
  {
    slug: "typologies-fintechs-afrique-francophone",
    title: "Quelles sont les différentes typologies de fintechs en Afrique francophone ?",
    date: "2023-02-06",
    author: "Kadder Ismael Toure",
    categories: ["fintech"],
    excerpt: "Panorama des acteurs et des services du secteur fintech en Afrique francophone.",
    blocks: [
      { t: "h2", c: "Qu'est-ce qu'une fintech ?" },
      { t: "p", c: "FinTech = Finance + Technology. Selon Larousse : « une start-up du secteur financier qui utilise les nouvelles technologies pour proposer des produits bancaires et financiers innovants, plus simples et moins onéreux »." },
      { t: "h2", c: "Principaux acteurs" },
      { t: "ul", c: [
        "Institutions bancaires agréées en digitalisation partielle ou totale (TymeBank, Orange Bank, Kuda).",
        "Fintechs pure-player, souvent en partenariat avec des banques, sur l'émission et la distribution de monnaie électronique.",
        "GAFAM (et BATX) étendus aux paiements, comptes, crédit.",
      ]},
      { t: "h2", c: "Principaux services" },
      { t: "ul", c: [
        "Services financiers numériques : paiements, monnaie électronique, transferts, wallets, mobile money, mobile banking.",
        "Assurance : souscription, gestion des sinistres, IA et big data pour le risque.",
        "Crypto-actifs : monnaies digitales sur blockchain, statut juridique flou.",
        "Financement participatif : crowdlending, dons, equity crowdfunding.",
        "Plateformes digitales optimisant l'offre bancaire classique.",
      ]},
      { t: "p", c: "L'émission de monnaie électronique occupe une place centrale dans l'écosystème des services financiers numériques en Afrique francophone, portée par des efforts réglementaires favorisant la transformation digitale." },
    ],
  },
  {
    slug: "autorisations-prealables-fintech",
    title: "Quelles sont les autorisations préalables à obtenir pour lancer une fintech en Afrique francophone ?",
    date: "2023-02-13",
    author: "Kadder Ismael Toure",
    categories: ["fintech"],
    excerpt: "Panorama des régimes d'autorisation par typologie d'activité fintech.",
    blocks: [
      { t: "p", c: "Les obligations réglementaires varient selon le type d'activité développée. Six catégories principales sont examinées." },

      { t: "h2", c: "1. Émission et distribution de monnaie électronique" },
      { t: "p", c: "Agrément individuel d'« établissement de monnaie électronique » requis auprès de l'autorité de régulation (banque centrale)." },
      { t: "h3", c: "Exigences essentielles" },
      { t: "ul", c: [
        "Forme juridique spécifique (SA, SARL, mutuelle, coopérative, GIE)",
        "Siège social dans la juridiction visée, objet social exclusif",
        "Capital minimum (ex. 300 millions FCFA zone UMOA)",
        "Comptes bancaires dédiés à la contrepartie de monnaie électronique",
        "Contrats de cantonnement et service clients",
        "Projections d'activité sur 3 ans (pessimiste, modeste, optimiste)",
        "Exigences techniques (disponibilité, intégrité, authentification, non-répudiation)",
        "Continuité d'activité, gestion des risques, interopérabilité",
        "Piste d'audit, procédures BCEAO",
      ]},
      { t: "h3", c: "Partenariat technique" },
      { t: "p", c: "Beaucoup de fintechs agissent comme « opérateurs techniques » partenaires d'émetteurs agréés (banques, établissements de paiement, microfinance). L'émetteur agréé reste responsable ; communications doivent l'identifier." },
      { t: "h3", c: "Nouveaux produits" },
      { t: "p", c: "Notification préalable à la banque centrale (typiquement 2 mois avant) avec projet, gestion des réclamations, LAB-FT, parties prenantes, processus, cartographie des risques, contrats." },

      { t: "h2", c: "2. Mobile banking, dépôts, retraits" },
      { t: "ul", c: [
        "Digital banking (néo-banque)",
        "Online banking (mutation partielle des banques traditionnelles)",
        "Collecte d'épargne et retraits",
      ]},
      { t: "p", c: "Agrément bancaire généralement requis." },

      { t: "h2", c: "3. Transfert rapide d'argent" },
      { t: "p", c: "Régi par la réglementation sur la gestion des moyens de paiement et la réception de fonds du public. Statut de « prestataire habilité » via agrément bancaire. À défaut, opérer en tant que mandataire d'un établissement agréé — sous validation des autorités." },

      { t: "h2", c: "4. InsurTech" },
      { t: "p", c: "Ce secteur est marqué par l'absence de cadre réglementaire et juridique spécifique à l'innovation. Les régulateurs avancent via la CIMA. Respecter les codes d'assurance tout en démontrant l'innovation." },

      { t: "h2", c: "5. Cryptomonnaies" },
      { t: "p", c: "Encadrement flou. Solliciter l'avis formel des autorités de régulation et de supervision pour éviter sanctions et risques LAB-FT." },

      { t: "h2", c: "6. Crowdfunding / crowdlending" },
      { t: "p", c: "Peu de cadres spécifiques. Maroc et Tunisie avancent notablement. Contacter les autorités pour autorisation et guidance." },

      { t: "p", c: "Les éléments listés ne constituent pas un conseil d'avocat." },
    ],
  },
  {
    slug: "obligations-reglementaires-fintech",
    title: "Quelles sont les principales obligations réglementaires d'une fintech en Afrique francophone ?",
    date: "2023-02-16",
    author: "Sonia Mavouna",
    categories: ["fintech"],
    excerpt: "Cybersécurité, données, LAB-FT et obligations client — le socle réglementaire post-lancement.",
    blocks: [
      { t: "h2", c: "Autorisations préalables" },
      { t: "p", c: "Certaines activités requièrent un agrément préalable. En cas de doute, consulter le régulateur et solliciter un avis formel." },
      { t: "h2", c: "Quatre domaines réglementaires majeurs" },
      { t: "ul", c: [
        "Cybersécurité — protection des données clients et infrastructures.",
        "Protection des données personnelles — information et consentement avant collecte.",
        "Prévention de la cybercriminalité — détection et politiques claires.",
        "LAB-FT — vérification d'identité, surveillance des transactions suspectes.",
      ]},
      { t: "h2", c: "Obligations client" },
      { t: "p", c: "Vérification d'identité avec pièces officielles avant transaction, archivage, devoir de diligence." },
      { t: "p", c: "La réglementation évolue : de nouveaux textes sectoriels sont en préparation (crowdfunding, émission de monnaie digitale)." },
    ],
  },
  {
    slug: "proteger-marque-oapi",
    title: "Comment protéger sa marque à l'OAPI : procédure, coûts et étapes",
    date: "2021-01-29",
    author: "Sonia Mavouna",
    categories: ["propriete-intellectuelle"],
    excerpt: "Protéger une marque, c'est en obtenir les droits exclusifs — procédure OAPI pas à pas.",
    blocks: [
      { t: "h2", c: "Qu'est-ce que l'OAPI ?" },
      { t: "p", c: "L'Organisation Africaine de la Propriété Intellectuelle est l'office régional basé à Yaoundé. Elle couvre 17 États membres d'Afrique francophone." },
      { t: "ul", c: [
        "Bénin, Burkina Faso, Cameroun, Centrafrique, Comores, Congo, Côte d'Ivoire, Gabon, Guinée, Guinée-Bissau, Guinée équatoriale, Mali, Mauritanie, Niger, Sénégal, Tchad, Togo",
      ]},
      { t: "p", c: "Un seul dépôt produit des effets automatiques dans l'ensemble des États membres." },
      { t: "h2", c: "Pourquoi déposer ?" },
      { t: "ol", c: [
        "Sécuriser son identité commerciale",
        "Empêcher un concurrent d'exploiter le nom",
        "Valoriser la startup lors d'une levée",
        "Créer un actif cessible ou licenciable",
      ]},
      { t: "h2", c: "Procédure détaillée" },
      { t: "h3", c: "1. Recherche d'antériorité" },
      { t: "p", c: "Vérifier qu'une marque similaire n'existe pas — évite opposition, annulation, perte d'investissement marketing." },
      { t: "h3", c: "2. Choix des classes (Nice)" },
      { t: "ul", c: [
        "Classe 35 : services commerciaux",
        "Classe 38 : télécommunications",
        "Classe 41 : médias / formation",
        "Classe 42 : services technologiques",
      ]},
      { t: "h3", c: "3. Dépôt officiel" },
      { t: "p", c: "Formulaire, reproduction de la marque, liste des classes, paiement des taxes." },
      { t: "h3", c: "4. Examen & publication" },
      { t: "p", c: "Examen de forme puis de fond. En moyenne 7 mois jusqu'à l'arrêté d'enregistrement, sous réserve d'absence d'irrégularité. Régularisation possible dans 3 mois." },
      { t: "h3", c: "5. Certificat d'enregistrement" },
      { t: "p", c: "Le certificat matérialise le droit de propriété ; l'arrêté consacre la décision d'enregistrement." },
      { t: "h2", c: "Documents requis" },
      { t: "ul", c: [
        "Demande adressée au directeur général de l'OAPI",
        "Formulaire M301 (reproduction, produits/services, coordonnées, couleurs)",
        "Justificatif de paiement",
        "Pouvoir du mandataire",
      ]},
      { t: "h2", c: "Coût (2026)" },
      { t: "ul", c: [
        "Taxes officielles de base : environ 360 000 FCFA",
        "Chaque classe supplémentaire = coût additionnel",
      ]},
      { t: "h2", c: "Durée" },
      { t: "p", c: "Protection de 10 ans à compter du dépôt, renouvelable indéfiniment par périodes de 10 ans." },
      { t: "h2", c: "Erreurs fréquentes" },
      { t: "ol", c: [
        "Déposer sans recherche préalable",
        "Choisir trop peu de classes",
        "Marque descriptive ou faible",
        "Confondre nom de domaine et protection juridique",
        "Attendre une levée de fonds pour régulariser",
      ]},
      { t: "h2", c: "OAPI vs ARIPO" },
      { t: "p", c: "OAPI : système unitaire — les 17 pays, ou rien. ARIPO : système à désignation — chaque État peut accepter ou refuser l'effet." },
    ],
  },
  {
    slug: "proteger-marque-tunisie",
    title: "Protéger sa marque en Tunisie",
    date: "2021-01-29",
    author: "Sonia Mavouna",
    categories: ["propriete-intellectuelle"],
    excerpt: "Procédure INNORPI, coûts, renouvellement — tout ce qu'il faut savoir pour déposer en Tunisie.",
    blocks: [
      { t: "h2", c: "Pourquoi déposer ?" },
      { t: "p", c: "L'enregistrement à l'INNORPI (Institut National de la Normalisation et de la Propriété Industrielle) confère la propriété exclusive et empêche les tiers d'utiliser la marque sans autorisation." },
      { t: "h2", c: "Étapes préalables" },
      { t: "ol", c: [
        "Identifier les classes de Nice applicables",
        "Rechercher la disponibilité via le service d'antériorité INNORPI",
        "Désigner un représentant tunisien pour les déposants étrangers",
        "Préparer le dossier (formulaire en double exemplaire, 5 spécimens de la marque max 10cm, liste des produits/services, justificatif de paiement, pouvoir du mandataire)",
      ]},
      { t: "h2", c: "Où déposer ?" },
      { t: "ul", c: [
        "Tunis : Cité El Khadhra, 1003 Tunis",
        "Sfax : 1 Rue Bejaya, 3002 Sfax",
        "Sousse : Rue Mongi Bali, Immeuble Hajri, 2e étage B24",
      ]},
      { t: "p", c: "Dépôt physique uniquement. Les documents supplémentaires peuvent être envoyés par courrier." },
      { t: "h2", c: "Coûts (TND TTC)" },
      { t: "ul", c: [
        "Dépôt initial (1 classe) : 595,600",
        "Renouvellement : 774,100",
        "Classe additionnelle au dépôt : 119,000",
        "Classe additionnelle au renouvellement : 178,500",
        "Certificat : 95,800",
        "Recherche d'antériorité : 36,300",
      ]},
      { t: "h2", c: "Examen et opposition" },
      { t: "p", c: "Examen de forme et de fond (distinctivité, ordre public). Publication au bulletin officiel dans les 12 mois, puis 2 mois d'opposition." },
      { t: "h2", c: "Enregistrement" },
      { t: "p", c: "Sans rejet ni opposition, inscription au registre national et remise du certificat." },
      { t: "h2", c: "Durée et renouvellement" },
      { t: "p", c: "10 ans, renouvelable indéfiniment par période de 10 ans par simple déclaration écrite si la marque n'est pas modifiée." },
      { t: "h2", c: "À l'international" },
      { t: "p", c: "Système de Madrid via l'INNORPI, UE via l'EUIPO, Afrique francophone via l'OAPI. Dépôt international dans les 6 mois pour bénéficier de la priorité." },
    ],
  },
  {
    slug: "proteger-marque-maroc",
    title: "Protéger sa propriété intellectuelle au Maroc",
    date: "2021-01-29",
    author: "Sonia Mavouna",
    categories: ["propriete-intellectuelle"],
    excerpt: "Procédure OMPIC, tarifs SME vs grandes structures, durée de protection.",
    blocks: [
      { t: "h2", c: "Démarches préalables" },
      { t: "p", c: "Identifier les classes (classification de Nice). Rechercher la marque dans la base OMPIC pour éviter les antériorités sur produits/services similaires." },
      { t: "h2", c: "Où déposer ?" },
      { t: "ul", c: [
        "Siège et délégations régionales de l'OMPIC",
        "Espaces dédiés à la Chambre de Commerce (CCI de Casablanca, CFCIM)",
        "En ligne sur marque.directompic.ma (tarifs réduits)",
      ]},
      { t: "h2", c: "Documents" },
      { t: "ul", c: [
        "Formulaire M1",
        "Deux reproductions noir et blanc, deux reproductions couleur",
        "Justificatif de paiement",
        "Pouvoir de représentation",
      ]},
      { t: "h2", c: "Procédure" },
      { t: "ol", c: [
        "Examen du dossier : récépissé, examen de forme et de fond, régularisation possible en 3 mois.",
        "Publication au catalogue officiel : 2 mois d'opposition.",
        "Enregistrement : certificat, protection 10 ans.",
      ]},
      { t: "h2", c: "Tarifs" },
      { t: "h3", c: "Tarif 1 (PME, indépendants, particuliers)" },
      { t: "ul", c: [
        "En ligne : 1 200 DH/classe ; 240 DH classes additionnelles",
        "Physique : 1 800 DH/classe ; 360 DH classes additionnelles",
      ]},
      { t: "h3", c: "Tarif 2 (autres)" },
      { t: "ul", c: [
        "En ligne : 1 800 DH/classe ; 360 DH classes additionnelles",
        "Physique : 2 400 DH/classe ; 480 DH classes additionnelles",
      ]},
      { t: "h2", c: "Durée & renouvellement" },
      { t: "p", c: "10 ans à compter du dépôt, renouvelable indéfiniment par tranches de 10 ans, dans les 6 mois précédant l'expiration." },
      { t: "h2", c: "À l'international" },
      { t: "p", c: "Système de Madrid via l'OMPIC (dépôt national préalable, désignation des États membres). Alternatives régionales : EUIPO, OAPI. Dépôt international idéalement dans les 6 mois pour bénéficier de la priorité." },
    ],
  },
  {
    slug: "donnees-personnelles-maroc-autorites",
    title: "Qui assure la protection de vos données personnelles au Maroc ? Les autorités compétentes",
    date: "2024-01-30",
    author: "ALF",
    categories: ["donnees-personnelles"],
    excerpt: "La CNDP, ses missions et ses pouvoirs — comprendre le régulateur marocain.",
    blocks: [
      { t: "h2", c: "Cadre légal" },
      { t: "p", c: "La loi n° 09-08 régit la protection des données personnelles au Maroc. Les données personnelles sont « toute information concernant une personne physique identifiée ou identifiable »." },
      { t: "p", c: "Tout traitement doit être déclaré à la CNDP avant sa mise en œuvre, sauf exclusion ou exemption. Les données sensibles (origine raciale/ethnique, opinions politiques, convictions religieuses, données génétiques ou de santé) requièrent une autorisation préalable. Les transferts hors Maroc requièrent une demande de transfert distincte." },
      { t: "h2", c: "La CNDP" },
      { t: "p", c: "La Commission Nationale de Contrôle de la Protection des Données à Caractère Personnel vérifie la licéité des traitements et le respect des libertés fondamentales. Adresse : Avenue Al Arz, Secteur 4, M1, Hay Riad, Rabat." },
      { t: "h3", c: "Exercer ses droits" },
      { t: "ul", c: [
        "Plainte en ligne sur le site CNDP",
        "Par email",
        "Par courrier (modèle fourni par la CNDP)",
      ]},
      { t: "h2", c: "Missions de la CNDP" },
      { t: "ul", c: [
        "Avis sur les projets de lois/règlements concernant les données personnelles",
        "Avis sur les fichiers de prévention des infractions",
        "Avis sur les projets statistiques",
        "Réception des notifications de représentants",
        "Réception des déclarations préalables et délivrance des récépissés",
        "Gestion des registres publics",
      ]},
      { t: "h2", c: "Pouvoirs" },
      { t: "ul", c: [
        "Enquête, investigation, accès aux lieux et données",
        "Ordonner communication des documents",
        "Ordonner modifications, verrouillage, effacement, destruction",
        "Interdire provisoirement ou définitivement un traitement",
      ]},
      { t: "h2", c: "Composition" },
      { t: "p", c: "7 membres. Président nommé par Sa Majesté le Roi, 6 membres sur proposition du Premier ministre et des présidents des deux Chambres. Mandat de 5 ans renouvelable." },
      { t: "h2", c: "Administration" },
      { t: "p", c: "Présidence avec convocation et direction des réunions (quorum deux tiers, décisions à la majorité, voix prépondérante en cas de partage). Un secrétaire général pilote le personnel, le budget, les marchés, les PV." },
      { t: "h2", c: "Statut des membres" },
      { t: "ul", c: [
        "Incompatibilité avec fonctions dirigeantes dans des entreprises de traitement",
        "Secret professionnel à vie",
        "Protection contre injures ou atteintes",
      ]},
    ],
  },
  {
    slug: "donnees-personnelles-burkina-faso",
    title: "Comprendre la protection des données personnelles au Burkina Faso",
    date: "2024-01-15",
    author: "André Agbevor",
    categories: ["donnees-personnelles"],
    excerpt: "Loi n°001-2021/AN et CIL — obligations pour les organisations traitant des données au Burkina.",
    blocks: [
      { t: "p", c: "La loi n° 001-2021/AN du 30 mars 2021 régit la protection des données personnelles au Burkina Faso. La Commission de l'informatique et des libertés (CIL) est l'autorité de régulation." },
      { t: "h2", c: "Champ d'application" },
      { t: "p", c: "La loi s'applique aux traitements automatisés ou non lorsque le responsable ou sous-traitant est établi au Burkina Faso ou relève de la juridiction burkinabè, et aux traitements mis en œuvre depuis le territoire national (hors données de transit)." },
      { t: "h3", c: "Exemptions" },
      { t: "ul", c: [
        "Traitement par un individu pour des activités exclusivement personnelles ou domestiques",
        "Copies temporaires techniques nécessaires à l'accès réseau",
        "Traitements journalistiques, artistiques ou littéraires (dans le respect de l'éthique professionnelle)",
      ]},
      { t: "h2", c: "Définitions clés" },
      { t: "p", c: "Donnée personnelle (article 5) : toute information concernant une personne physique identifiée ou identifiable directement ou indirectement. Traitement : toute opération automatisée ou non appliquée à ces données (collecte, organisation, stockage, adaptation, modification, etc.)." },
      { t: "h2", c: "Formalités préalables" },
      { t: "h3", c: "Exemptions" },
      { t: "ul", c: [
        "Archivage limité",
        "Organisations à but non lucratif (cultuelles, philosophiques, politiques, syndicales) limitées à leurs membres",
      ]},
      { t: "h3", c: "Régimes" },
      { t: "ol", c: [
        "Déclaration normale",
        "Autorisation préalable (données génétiques/biométriques, recherche santé, infractions, interconnexion, NIN, données d'intérêt public, décisions individuelles algorithmiques, transferts internationaux)",
        "Acte législatif ou réglementaire pour les entités publiques ou privées gérant un service public dans certains cas",
      ]},
      { t: "h2", c: "Procédures" },
      { t: "p", c: "Déclarations électroniques ou papier adressées à la CIL. Récépissé sans délai sauf décision contraire." },
      { t: "h2", c: "Sanctions" },
      { t: "ul", c: [
        "Entrave à la CIL ou refus d'information : 5 à 10 millions FCFA",
        "Traitement sans formalités, dépassement de durée, divulgation non autorisée : 5 à 20 millions",
        "Détournement de finalité, collecte frauduleuse : 5 à 100 millions",
        "Traitement malgré opposition légitime : 2 à 5 millions",
        "Conservation de données sensibles sans consentement : 10 à 100 millions",
      ]},
      { t: "p", c: "La CIL peut aussi confisquer des supports matériels et interdire la gestion de traitements pendant 2 ans." },
      { t: "h2", c: "Responsabilités" },
      { t: "p", c: "La startup est responsable de traitement si elle décide des finalités ; sous-traitant si elle agit pour le compte d'un autre. Obligations de sécurité et confidentialité pour les deux. Contrat obligatoire avec le sous-traitant." },
      { t: "h2", c: "Avantages de la conformité" },
      { t: "p", c: "Différenciation compétitive nationale et internationale, réputation, image de marque démontrant une gestion exemplaire." },
    ],
  },
  {
    slug: "donnees-personnelles-cote-divoire",
    title: "Comprendre la protection des données personnelles en Côte d'Ivoire",
    date: "2024-01-08",
    author: "André Agbevor",
    categories: ["donnees-personnelles"],
    excerpt: "Loi n° 2013-450 et ARTCI — obligations et sanctions pour les entreprises ivoiriennes.",
    blocks: [
      { t: "p", c: "La loi n° 2013-450 du 19 juin 2013 régit la protection des données personnelles en Côte d'Ivoire. L'ARTCI (Autorité de Régulation des Télécommunications/TIC) est l'autorité compétente." },
      { t: "h2", c: "Champ d'application" },
      { t: "ul", c: [
        "Collecte, traitement, transmission, stockage ou usage par personne physique, État, collectivité, personne morale publique ou privée",
        "Traitements automatisés ou non dans des fichiers",
        "Traitements opérés sur le territoire national",
        "Traitements liés à la sécurité publique, défense, recherche pénale, sécurité de l'État (sous dérogations)",
      ]},
      { t: "p", c: "Exemptions : traitements exclusivement personnels ou domestiques (si les données ne sont pas partagées/diffusées) ; copies techniques temporaires nécessaires à l'accès réseau." },
      { t: "h2", c: "Définitions" },
      { t: "p", c: "Donnée personnelle (article 1) : toute information, quel que soit le support, relative à une personne physique identifiée ou indirectement identifiable." },
      { t: "h2", c: "Obligations" },
      { t: "h3", c: "Formalités dispensées" },
      { t: "ul", c: [
        "Traitement strictement personnel/domestique",
        "Données naturellement publiques (obligations légales)",
        "Registres à usage privé",
        "Responsable ayant désigné un DPO indépendant",
      ]},
      { t: "h3", c: "Déclaration préalable obligatoire" },
      { t: "p", c: "Tout traitement requiert une déclaration préalable à l'ARTCI. Le récépissé permet de démarrer." },
      { t: "h3", c: "Autorisation préalable" },
      { t: "ul", c: [
        "Données génétiques, médicales, recherche scientifique dans ces domaines",
        "Données sur infractions, condamnations, sécurité",
        "Numéros d'identification nationaux ou équivalents",
        "Biométrie",
        "Données d'intérêt public",
        "Transferts internationaux",
      ]},
      { t: "h2", c: "Procédures" },
      { t: "p", c: "Dossier au président de l'ARTCI (courrier ou équivalent avec accusé de réception) : ARTCI – Marcory Anoumanbo – B.P. 2203 – Abidjan 18. Formulaires disponibles sur autoritedeprotection.ci. Décision dans un délai d'un mois, prorogeable d'un mois avec justification écrite." },
      { t: "h2", c: "Pouvoirs de l'ARTCI" },
      { t: "ul", c: [
        "Avertissement, mise en demeure",
        "Interruption ou verrouillage de traitements",
        "Interdictions temporaires ou définitives",
        "Retrait d'autorisations",
        "Sanctions pécuniaires",
      ]},
      { t: "p", c: "Les violations sont également punissables par le code pénal ivoirien." },
      { t: "h2", c: "Responsabilités" },
      { t: "p", c: "Responsable de traitement ou sous-traitant : obligations de sécurité, information, consentement, réponse aux demandes, compatibilité technique. Sélection de sous-traitants offrant des garanties suffisantes." },
      { t: "h2", c: "Sanctions pécuniaires" },
      { t: "p", c: "Première sanction : jusqu'à 10 000 000 FCFA. Récidive dans les 5 ans : jusqu'à 100 000 000 FCFA, ou 5% du CA HT (plafonné à 500 000 000 FCFA)." },
    ],
  },
  {
    slug: "donnees-personnelles-senegal",
    title: "Comprendre la protection des données personnelles au Sénégal",
    date: "2023-05-11",
    author: "Sonia Mavouna",
    categories: ["donnees-personnelles"],
    excerpt: "Loi n° 2008-12 et CDP — obligations et autorisation de traitement au Sénégal.",
    blocks: [
      { t: "p", c: "La loi n° 2008-12 du 25 janvier 2008 régit la protection des données personnelles au Sénégal. La CDP (Commission de Protection des Données Personnelles) est l'autorité compétente." },
      { t: "h2", c: "Champ d'application" },
      { t: "p", c: "Toute entité qui traite des données personnelles sur le territoire sénégalais, ou qui traite des données de personnes situées au Sénégal, quel que soit son siège." },
      { t: "h3", c: "Définition" },
      { t: "p", c: "Donnée personnelle (article 4) : toute information relative à une personne physique identifiée ou identifiable par référence à un numéro d'identification ou à des éléments propres à son identité physique, physiologique, génétique, psychique, culturelle, sociale ou économique." },
      { t: "h2", c: "Obligations" },
      { t: "h3", c: "Déclaration préalable (article 18)" },
      { t: "p", c: "Tout traitement doit être déclaré à la CDP avant mise en œuvre. Récépissé de dépôt délivré, puis récépissé autorisant l'implémentation dans un délai d'un mois (prorogeable)." },
      { t: "h3", c: "Autorisation préalable (données sensibles)" },
      { t: "p", c: "Religion, philosophie, politique, syndicat, vie sexuelle, race, santé, mesures d'ordre social, poursuites, sanctions. Décision CDP dans 2 mois (prorogeable). Silence = accord tacite." },
      { t: "h3", c: "Obligations envers clients et salariés" },
      { t: "ul", c: [
        "Collecte pour finalités déterminées, explicites, légitimes",
        "Consentement préalable",
        "Sécurité et confidentialité (mesures techniques et organisationnelles)",
        "Droits d'accès, de rectification, d'effacement",
        "Notification de violation au régulateur et aux personnes",
        "Sous-traitants tenus aux mêmes obligations",
      ]},
      { t: "h2", c: "Pouvoirs de la CDP" },
      { t: "ul", c: [
        "Registre des traitements autorisés",
        "Réception de plaintes et pétitions",
        "Information du Procureur en cas d'infraction",
        "Contrôles sur pièces et sur place",
        "Sanctions après procédure contradictoire",
      ]},
      { t: "h3", c: "Mesures en cas de non-conformité" },
      { t: "ul", c: [
        "Avertissement ou injonction écrite",
        "Retrait provisoire de 3 mois (définitif à l'expiration)",
        "Amende : 1 à 100 millions FCFA",
        "Interruption/blocage 3 mois en cas d'urgence",
      ]},
    ],
  },
  {
    slug: "rgpd-informer-personnes-concernees",
    title: "RGPD — comment informer les personnes concernées ?",
    date: "2021-10-06",
    author: "Kelly Hazan",
    categories: ["donnees-personnelles"],
    excerpt: "Articles 13 et 14 du RGPD : ce qu'il faut dire aux personnes dont vous traitez les données.",
    blocks: [
      { t: "h2", c: "Obligation" },
      { t: "p", c: "Articles 13 et 14 du RGPD : le responsable de traitement doit informer les personnes dont les données sont traitées, qu'elles soient collectées directement ou indirectement." },
      { t: "h2", c: "Informations à transmettre" },
      { t: "ul", c: [
        "Identité et coordonnées du responsable",
        "Coordonnées du DPO (le cas échéant)",
        "Finalités du traitement",
        "Base légale",
        "Caractère obligatoire ou facultatif",
        "Destinataires ou catégories de destinataires",
        "Transferts internationaux et garanties",
        "Durée de conservation",
        "Droits (accès, rectification, effacement, limitation, opposition, portabilité)",
        "Droit de retirer le consentement",
        "Droit de porter plainte auprès d'une autorité",
        "Décision automatisée et profilage",
        "En collecte indirecte : catégories de données et sources",
      ]},
      { t: "p", c: "En France, l'article 116 de la loi Informatique et Libertés exige des mentions spécifiques sous les formulaires et questionnaires." },
      { t: "h2", c: "Forme" },
      { t: "p", c: "L'information doit être lisible, facilement accessible, claire et compréhensible. Formats acceptés :" },
      { t: "ul", c: [
        "Politique de confidentialité du site",
        "Politique interne salariés",
        "Mentions sur formulaires, factures, emails",
        "Clauses dans contrats de travail, clients, fournisseurs",
      ]},
      { t: "h2", c: "Conseils" },
      { t: "ul", c: [
        "Ne pas copier une politique existante inadaptée",
        "Langage lisible, clair, compréhensible",
        "Informer à plusieurs étapes du parcours utilisateur",
        "Prioriser l'essentiel à la création de compte",
        "Liens vers la politique complète",
        "Mettre à jour régulièrement",
      ]},
      { t: "h2", c: "Sanctions" },
      { t: "p", c: "Jusqu'à 4 % du CA mondial ou 20 millions d'euros (le plus élevé des deux)." },
    ],
  },
  {
    slug: "rgpd-violations-donnees-startup",
    title: "RGPD — violations de données, quelles sont les obligations de ma start-up ?",
    date: "2021-10-02",
    author: "Kelly Hazan",
    categories: ["donnees-personnelles"],
    excerpt: "Notification CNIL sous 72h, information des personnes concernées, registre des violations.",
    blocks: [
      { t: "h2", c: "Qu'est-ce qu'une violation ?" },
      { t: "p", c: "Toute action intentionnelle ou non compromettant confidentialité, intégrité ou disponibilité des données personnelles (article 33 du RGPD). Exemples : perte de documents, accès non autorisé à une base. Une faille de sécurité est plus large — elle ne touche pas forcément les données personnelles." },
      { t: "h2", c: "Obligations du responsable de traitement" },
      { t: "h3", c: "Notification à l'autorité (72h)" },
      { t: "p", c: "Sous 72 heures après découverte. En France, via le formulaire CNIL. Justifier tout retard. Une notification complémentaire peut suivre." },
      { t: "h3", c: "Information des personnes concernées" },
      { t: "p", c: "Dès que possible si risque élevé pour leurs droits et libertés. Contenu : description claire, coordonnées DPO, conséquences probables, mesures correctives." },
      { t: "h3", c: "Exceptions à la notification individuelle" },
      { t: "ul", c: [
        "Mesures techniques appropriées (chiffrement, pseudonymisation)",
        "Mesures ultérieures garantissant que le risque élevé ne se matérialisera pas",
        "Effort disproportionné → communication publique",
      ]},
      { t: "h3", c: "Registre des violations" },
      { t: "p", c: "Tenue continue, documentation de toutes les violations." },
      { t: "h2", c: "Obligations du sous-traitant" },
      { t: "p", c: "Informer le responsable dès que possible. Les délais peuvent être contractuels (ex. 48h dans les accords article 28)." },
      { t: "h2", c: "Sanctions" },
      { t: "p", c: "Jusqu'à 20 millions d'euros ou 4 % du CA annuel mondial, sanctions publiques. Réputation, confiance client, partenaires. En France : jusqu'à 5 ans de prison et 1,5 million d'euros pour les personnes morales." },
    ],
  },
  {
    slug: "rgpd-mise-en-conformite-startups-africaines",
    title: "RGPD — apprenez à vous mettre en conformité",
    date: "2021-09-06",
    author: "Kelly Hazan",
    categories: ["donnees-personnelles"],
    excerpt: "Les startups africaines sont aussi concernées par le RGPD dès qu'elles ciblent des résidents de l'UE.",
    blocks: [
      { t: "h2", c: "Étape 1 — Traitez-vous des données personnelles ?" },
      { t: "p", c: "Le RGPD couvre les traitements automatisés en tout ou partie ainsi que les traitements non automatisés contenus dans des fichiers. Donnée personnelle = toute information relative à une personne physique identifiée ou identifiable." },
      { t: "p", c: "Exemples : recrutement, gestion RH, prospection commerciale, gestion client." },
      { t: "h2", c: "Étape 2 — Êtes-vous soumis au RGPD ?" },
      { t: "ol", c: [
        "Vous offrez des biens ou services à des résidents UE (gratuits ou payants) — e-commerce accessible aux personnes UE.",
        "Vous suivez le comportement de résidents UE dans l'UE — cookies, profilage.",
      ]},
      { t: "p", c: "Les autorités européennes peuvent contrôler à distance, sur pièces, sur place ou par audition." },
      { t: "h2", c: "Étape 3 — Qualification" },
      { t: "ul", c: [
        "Responsable de traitement : détermine les finalités et moyens",
        "Sous-traitant : traite pour le compte du responsable",
      ]},
      { t: "h2", c: "Étape 4 — Obligations" },
      { t: "ol", c: [
        "Désigner un représentant UE par écrit",
        "Mettre en œuvre les principes (registre, politique)",
        "Contractualiser les relations (responsables, sous-traitants, partenaires)",
        "Sécurité des données (procédures, gestion des violations)",
        "Encadrer les transferts hors UE",
      ]},
      { t: "p", c: "Nommer un DPO si nécessaire." },
      { t: "h2", c: "Pourquoi se conformer ?" },
      { t: "p", c: "Sanctions jusqu'à 20 millions d'euros ou 4 % du CA mondial, publiques. France : jusqu'à 5 ans de prison et 1,5 M€ pour les personnes morales. Bénéfice business : différenciation et confiance." },
    ],
  },
  {
    slug: "rgpd-registres-activites-traitement",
    title: "Comment réaliser ses registres des activités de traitement au regard du RGPD ?",
    date: "2021-09-06",
    author: "Kelly Hazan",
    categories: ["donnees-personnelles"],
    excerpt: "L'article 30 du RGPD impose un registre — ce qu'il doit contenir et comment le tenir.",
    blocks: [
      { t: "h2", c: "Obligation" },
      { t: "p", c: "Le RGPD a supprimé l'autorisation préalable et l'a remplacée par un principe d'accountability. L'une des obligations clés : tenir des registres des activités de traitement." },
      { t: "h2", c: "Étapes préalables" },
      { t: "h3", c: "1. Identifier les traitements" },
      { t: "ul", c: [
        "Former le personnel à la protection des données",
        "Inclure tous les projets en cours dans la cartographie",
        "Identifier les départements concernés",
        "Poser des questions ciblées",
      ]},
      { t: "h3", c: "2. Qualification" },
      { t: "ul", c: [
        "Responsable — détermine les finalités et moyens",
        "Sous-traitant — traite pour le compte du responsable",
        "Responsable conjoint — responsabilité partagée",
      ]},
      { t: "p", c: "Chaque qualification exige un registre séparé." },
      { t: "h3", c: "3. Contenu" },
      { t: "h4", c: "Responsable" },
      { t: "ul", c: [
        "Nom et coordonnées",
        "Finalités",
        "Catégories de personnes concernées et de données",
        "Destinataires (y compris pays tiers)",
        "Durée de conservation",
        "Mesures techniques et organisationnelles de sécurité",
      ]},
      { t: "h4", c: "Sous-traitant" },
      { t: "ul", c: [
        "Nom et coordonnées",
        "Catégories de traitements pour chaque responsable",
        "Transferts internationaux",
        "Mesures de sécurité",
      ]},
      { t: "h3", c: "4. Recommandations" },
      { t: "ul", c: [
        "Inclure uniquement l'information strictement nécessaire",
        "Format approprié (Excel, Word, logiciel dédié)",
        "Export/impression rapide pour les autorités",
        "Accès restreint",
        "Mise à jour au moins tous les 6 mois",
      ]},
      { t: "h2", c: "Pourquoi ?" },
      { t: "p", c: "Visibilité des traitements, accountability, identification des traitements nécessitant une AIPD. Sanctions : jusqu'à 2 % du CA mondial ou 10 millions d'euros." },
    ],
  },
  {
    slug: "startups-ivoiriennes-conformite-donnees-personnelles",
    title: "Startups ivoiriennes : se mettre en conformité avec la loi de protection des données",
    date: "2021-08-20",
    author: "Annick Imboua-Niava",
    categories: ["donnees-personnelles"],
    excerpt: "Loi n° 2013-450 et ARTCI — guide pratique pour startups ivoiriennes.",
    blocks: [
      { t: "h2", c: "Étape 1 — Traitez-vous des données personnelles ?" },
      { t: "p", c: "Selon la loi 2013-450, le traitement couvre toute opération automatisée ou non (collecte, exploitation, enregistrement, organisation, conservation, adaptation, modification, sauvegarde, copie, suppression...). Donnée personnelle : toute information relative à une personne physique identifiée ou identifiable directement ou indirectement." },
      { t: "p", c: "Activités courantes : paie, e-commerce, marketing, CRM, campagnes email, enregistrement IP, vidéosurveillance." },
      { t: "h2", c: "Étape 2 — Obligations vis-à-vis de l'ARTCI" },
      { t: "p", c: "Déclaration préalable à toute activité, procédure ARTCI, engagement de conformité. Décision dans un délai d'un mois, prorogeable d'un mois. Implémentation possible sur réception du récépissé." },
      { t: "h3", c: "Données sensibles" },
      { t: "p", c: "Autorisation préalable obligatoire : infractions, condamnations, NIN (y compris numéros de téléphone), transferts vers pays tiers, données génétiques/médicales." },
      { t: "h2", c: "Étape 3 — Qualification" },
      { t: "ul", c: [
        "Responsable — détermine collecte et finalités",
        "Sous-traitant — traite pour le compte d'un autre",
      ]},
      { t: "h2", c: "Sanctions" },
      { t: "ul", c: [
        "Retrait provisoire ou définitif de l'autorisation",
        "Amendes administratives",
      ]},
      { t: "p", c: "Standard : jusqu'à 10 000 000 FCFA. Récidive dans les 5 ans : jusqu'à 5 % du CA HT (plafond 500 000 000 FCFA)." },
      { t: "h2", c: "Bénéfices de la conformité" },
      { t: "p", c: "Différenciation nationale et internationale, réputation, image de marque, confiance client." },
    ],
  },
  {
    slug: "declarer-traitements-donnees-personnelles-maroc",
    title: "Déclarer ses traitements de données personnelles au Maroc",
    date: "2021-08-11",
    author: "Kelly Hazan",
    categories: ["donnees-personnelles"],
    excerpt: "Loi 09-08 et CNDP — formulaires F211 / F214 pour déclarer au Maroc.",
    blocks: [
      { t: "h2", c: "Quand votre startup traite-t-elle des données ?" },
      { t: "p", c: "Dès qu'elle gère des campagnes marketing, de la paie, de la facturation, un e-commerce. Données concernées : nom, identifiants, emails, photos, téléphone, empreintes, ADN, coordonnées bancaires — toute information identifiant ou susceptible d'identifier une personne." },
      { t: "h3", c: "Exemples de finalités" },
      { t: "ul", c: [
        "Gestion du personnel et de la paie",
        "Accès à une base clients (CRM)",
        "Distribution d'emails promotionnels",
        "Destruction de documents contenant des données personnelles",
        "Publication de photos sur le site",
        "Stockage d'IP et d'adresses MAC",
        "Vidéosurveillance",
      ]},
      { t: "p", c: "Loi 09-08 du 18 février 2009 applicable à tout traitement dont le responsable ou les moyens sont au Maroc." },
      { t: "h2", c: "Obligations CNDP" },
      { t: "p", c: "Toute collecte doit être déclarée à la CNDP avant mise en œuvre, sauf exclusion/exemption." },
      { t: "p", c: "Données sensibles (race, opinions, religion, syndicat, génétique, santé, NIN) : autorisation préalable. Transferts hors Maroc : autorisation distincte." },
      { t: "h2", c: "Procédure" },
      { t: "h3", c: "Étape 1" },
      { t: "p", c: "Formulaire F211 (déclaration normale) ou F214 (simplifiée) avec pouvoir du signataire, copie de sa CIN, autres documents pertinents." },
      { t: "h3", c: "Étape 2" },
      { t: "ul", c: [
        "Récépissé CNDP sous 24 heures",
        "Notification dans 8 jours si une autorisation préalable est requise",
      ]},
      { t: "p", c: "Les délais courent après fourniture complète des informations." },
      { t: "h2", c: "Importance de la conformité" },
      { t: "p", c: "Évite sanctions financières et poursuites pénales. Avantage compétitif. Démontre une gestion exemplaire et renforce la réputation." },
    ],
  },
];

export const articlesBySlug: Record<string, Article> =
  Object.fromEntries(articles.map((a) => [a.slug, a]));

export const articlesByCategory: Record<ArticleCategory, Article[]> = {
  "levee-de-fonds": articles.filter((a) => a.categories.includes("levee-de-fonds")),
  "pacte-dactionnaires": articles.filter((a) => a.categories.includes("pacte-dactionnaires")),
  "fintech": articles.filter((a) => a.categories.includes("fintech")),
  "donnees-personnelles": articles.filter((a) => a.categories.includes("donnees-personnelles")),
  "propriete-intellectuelle": articles.filter((a) => a.categories.includes("propriete-intellectuelle")),
};
